# essential libraries
library(broom)
library(corrr)
library(distributional)
library(downlit)
library(downloadthis)
library(ggdist)
library(ggResidpanel)
library(janitor)
library(kableExtra)
library(knitr)
library(patchwork)
library(pwr)
library(reticulate)
library(rstatix)
library(tidyverse)
#library(powerAnalysis)
theme_set(theme_bw())
